class error_handling:
    def __init__(self):
        pass
